// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./providers/ReduxProvider";
import { ModalProvider } from "./providers/ModalContext";
import Modal from "./components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "PEPTIDE.CLUB - Research Peptides",
    description: "Premium Peptides Delivered",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <meta property="og:title" content="PEPTIDE.CLUB" />
                <meta property="og:description" content="Premium Peptides Delivered" />
                <meta property="og:image" content="https://peptide.club/assets/peptide-social.png" />
                <meta property="og:url" content="https://peptide.club" />
                <meta property="og:type" content="website" />
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:title" content="PEPTIDE.CLUB" />
                <meta name="twitter:description" content="Premium Peptides Delivered" />
                <meta name="twitter:image" content="https://peptide.club/assets/peptide-social.png" />
            </head>
            <body className={`${inter.className}`} style={{ fontFamily: "system-ui, -apple-system, sans-serif" }}>
                <ReduxProvider>
                    <ModalProvider>
                        {children}
                        <Modal />
                    </ModalProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
